# Generated by Django 3.0.10 on 2020-09-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200901_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_git_id', models.CharField(max_length=100)),
                ('user_redmine', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
