# Generated by Django 3.0.10 on 2020-09-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userc',
        ),
    ]
