# Generated by Django 3.0.10 on 2020-10-22 15:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kubernets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_description', models.TextField()),
                ('Name', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Deactivate', 'Deactivate')], max_length=200, null=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota', models.CharField(blank=True, max_length=100)),
                ('CPU', models.CharField(blank=True, max_length=100)),
                ('Memory', models.CharField(blank=True, max_length=100)),
                ('Limit_cpu', models.CharField(blank=True, max_length=100)),
                ('Limit_memory', models.CharField(blank=True, max_length=100)),
                ('choice_quota', models.CharField(blank=True, choices=[('Business', 'Business'), ('Mobile', 'Mobile'), ('Ess', 'Ess')], max_length=200)),
                ('namespace', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Kubernets', verbose_name='Namespaces')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Project_name', models.CharField(max_length=100)),
                ('gitlab_id', models.CharField(max_length=100)),
                ('redmine_id', models.CharField(max_length=100)),
                ('Identifiat', models.CharField(max_length=100)),
                ('gitlab_member', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('Project_URL', models.CharField(max_length=100)),
                ('name_customer', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(default=datetime.date.today)),
                ('visibility_Level', multiselectfield.db.fields.MultiSelectField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Internel', 'Internel')], max_length=23)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True)),
                ('author', models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permissionproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Choose_a_role_permission', models.CharField(choices=[('50', 'Manager'), ('20', 'Reporter'), ('30', 'Developer'), ('0', 'No access')], max_length=200, null=True)),
                ('expires_at', models.DateTimeField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Post', verbose_name='Projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User member')),
            ],
        ),
    ]
